language:
  - cpp
sudo: required
dist: trusty
# compiler:
#  - gcc
#  - clang
env:
  global:
    - GCC_VERSION=7
    - LIBSTDC_VERSION=7

before_install:
#   - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
#   - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-4.0 main" | sudo tee -a /etc/apt/sources.list
#   - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/jonathonf/gcc-7.1/ubuntu/ trusty main" | sudo tee -a /etc/apt/sources.list
#   - sudo add-apt-repository --yes ppa:jonathonf/gcc-7.1
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
#   - sudo apt-get -qq install build-essential
#   - sudo apt-get -qq --allow-unauthenticated install libstdc++-${LIBSTDC_VERSION}-dev
#   - sudo apt-get -qq --allow-unauthenticated install clang-3.5
  - sudo apt-get install gcc-7 g++-7

script:
  - g++-${GCC_VERSION} -std=gnu++1z -Wall -Wextra -pedantic test/zubera.cpp && ./a.out
#   - clang++-3.5 -std=gnu++1z -Wall -Wextra -pedantic test/zubera.cpp.cpp && ./a.out

